os:
  - linux
# - osx


language: python

python:
  - "3.4"
  - "3.5"

# command to install dependencies
install:
  - pip install tox-travis
  - python setup.py install

# command to run tests
script: tox